### ISSUE TITLE
Add anchor for every style rule

### ISSUE THREAD

**Issue by JuanitoFatas** [JuanitoFatas/ruby-style-guide#39]
![screenshot 2015-04-06 22 33 08](https://cloud.githubusercontent.com/assets/1000669/7005682/ed98ae42-dcac-11e4-9344-212347739482.png)

Those `[link]` superscripts.

**Comment by franklinyu** [comment]
Same link as Original version?

**Comment by JuanitoFatas** [comment]
> Same href as original version?

Yes please!

**Comment by JuanitoFatas** [comment]
zh-CN is done.

Need to work on zh-TW.
