### ISSUE TITLE
保护你的项目被 Windows 的行编码侵入

### ISSUE THREAD

**Issue by JasonSi** [JuanitoFatas/ruby-style-guide#68]
使用 Unix 风格的行编码(缺省涵盖 BSD/Solaris/Linux/OSX 的用户，Windows 用户要格外小心。) 如果你使用 Git ，你也许会想加入下面这个配置，**来保护你的项目被 Windows 的行编码侵入**

保护项目被侵入，感觉像是病句的吧。 **protect ... from ...** 主流翻译还是会说**保护...不被（免受）侵入**等等 
拙见 见谅

**Comment by 0x01f7** [comment]
你说的是繁体中文版本吧？刚才读了下，貌似确实像是少了个“不”字。 @JuanitoFatas

**Comment by JasonSi** [comment]
嗯 小细节啦
翻译得很棒的 ～

——Jason's iPhone

**Comment by JuanitoFatas** [comment]
Thanks for the feedback.
